site_name: WFX Documentation
site_description: Explicit, low-level C++ web framework

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link

extra_css:
  - css/code_format.css
  - css/scrollbar_format.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - First Program: getting_started/first_program.md
  - Core Concepts:
    - Project Structure: core_concepts/project_structure.md
    - Engine Commands: core_concepts/engine_commands.md
    - WFX Settings: core_concepts/wfx_toml.md
  - API Reference:
    - Overview: api_reference/overview.md
    - Request & Response: api_reference/request_and_response.md
    - Routing: api_reference/routing.md
    - Middleware: api_reference/middleware.md
    - Constructor: api_reference/constructor.md
    - Async: api_reference/async.md
    - Templates: api_reference/templates.md
    - Forms: api_reference/forms.md
    - Json: api_reference/json.md